language: php

notifications:
  email:
    recipients:
        - rdebleu@eWallah.net

sudo: required

addons:
  firefox: "47.0.1"
  postgresql: "9.6"
  apt:
    packages:
      - oracle-java8-installer
      - oracle-java8-set-default
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 5.6
 - 7.0
 - 7.1

env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
 
matrix:
 exclude:
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - php: 5.6
    env: DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 5.6
    env: DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - php: 7.0
    env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - php: 7.0
    env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - php: 7.1
    env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - php: 7.1
    env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
    
before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 8.9
  - nvm use 8.9
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  #- moodle-plugin-ci savepoints
  #- moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit --coverage-clover
  - moodle-plugin-ci behat
  - moodle-plugin-ci behat --profile chrome

after_success:
  - moodle-plugin-ci coveralls-upload
